### ISSUE TITLE
Timestamp from device

### ISSUE THREAD

**Issue by bobans** [theIoTLab/ZephyrBHDeviceAdapter#1]
Timestamp from device is one month ahead.
Your TimeConverter class creates GregorianCalendar with month which is integer sent from the sensor. Sensor sends months starting from 1 and GregorianCalendar uses months starting from 0.

**Comment by marcello-morena** [comment]
We are investigating. Thanks for reporting this bug.

**Comment by marcello-morena** [comment]
This has been fixed. Please check [version 3.4.2](https://github.com/theIoTLab/ZephyrBHDeviceAdapter/releases/tag/v3.4.2).
