### ISSUE TITLE
R to R data

### ISSUE THREAD

**Issue by bobans** [theIoTLab/ZephyrBHDeviceAdapter#3]
The Zephyr documentation says "Alternating ± sign at new
detection".

From the Zephyr BH Device Adapter and Protocol Adapter I receive only positive values. There are values about 1000 and 64000 when sign is altered.

Casting data from the sensor to short may help.

**Comment by marcello-morena** [comment]
I've merged your pull request about this bug (https://github.com/theIoTLab/ZephyrBHDeviceAdapter/commit/eedf2463e5770fb310d24a65e495c4af98a34f93). This should now be fixed.
